### ISSUE TITLE
Fix carlos's link to the profile

### ISSUE THREAD

**Issue by earlduque** [ServiceNowDevProgram/Hacktoberfest#20]
When I made the 2024 update, I didn't know Carlos' github profile yet so it's just a dead link.

Need to update it to go to https://github.com/kmxo

Remember, updates to the readme file should be done to the [TEMPLATE file](https://github.com/ServiceNowDevProgram/Hacktoberfest/blob/main/.github/templates/rootreadmetemplate.md), not the readme file (see the contributing guidelines)

**Comment by df-bhavesh** [comment]
@earlduque  Assign this issue to me

**Comment by snamjosh** [comment]
Closing this issue since https://github.com/ServiceNowDevProgram/Hacktoberfest/pull/21 is merged.

**Comment by kmxo** [comment]
It's working.  
Thank you @snamjosh!
