### ISSUE TITLE
Create a code of conduct

### ISSUE THREAD

**Issue by earlduque** [ServiceNowDevProgram/Hacktoberfest#25]
We should have a CODE_OF_CONDUCT.MD on this repo (at a minimum).
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project

**Comment by tejasathalye** [comment]
hey @earlduque can you assign it to me? I can do the task right away!

**Comment by rahulgithub-web** [comment]
Hey @earlduque  Please assign this task to me and also add a `hacktoberfest` label to it.

**Comment by devalcodes** [comment]
@Lacah Code Of Conduct md file updated
